### ISSUE TITLE
Consider using queue interprop as abstraction for queues 

### ISSUE THREAD

**Issue by makasim** [narrowspark/framework#662]
Hello!

Please look at https://github.com/queue-interop/queue-interop project. Using interfaces from it allows us reuse some implementations like enqueue, which supports a lot of transports. You can outsource some code

**Comment by prisis** [comment]
Im outsourcing all of the connections and jobs to enqueue  :), see #622 (started to work on it)

**Comment by makasim** [comment]
great! can I be of help?

**Comment by prisis** [comment]
Im just thinking about a easy queue component api with less code to wirte for the end user.

Ideas are welcome :)
